struct CanFrame 
{
    // nanosecond timestamp
    uint64 timestamp;
    // CAN message id 
    uint32 id;
    // CAN data size in bytes , up to 8 bytes
    uint8  dlc;
    // reserved bytes
    uint8  reserved[3];
    // CAN data
    uint8  data[8];
};